
import javax.swing.JFrame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.sql.*;
import javax.mail.Authenticator;
import javax.mail.Session;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Random;
import javax.mail.Session;
import javax.mail.Message.RecipientType;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.*;
import java.net.PasswordAuthentication;
import javax.mail.Message;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajendra Sharma
 */

public class LoginForm extends javax.swing.JFrame {
    String pass="";
    int OTP;
    int i=0;
    
    
        /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);//center form in the screen
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton_CANCEL = new javax.swing.JButton();
        jButton_LOGIN = new javax.swing.JButton();
        jLabelRegisterx = new javax.swing.JLabel();
        jLabelRegister1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton62 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jLabelRegister2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelClose.setText("x");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Login Form");

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addGap(34, 34, 34)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMin))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mail ID");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 50, 80, 30);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(160, 50, 480, 30);

        jButton_CANCEL.setBackground(new java.awt.Color(242, 38, 19));
        jButton_CANCEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_CANCEL.setForeground(new java.awt.Color(255, 255, 255));
        jButton_CANCEL.setText("Cancel");
        jButton_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CANCELActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_CANCEL);
        jButton_CANCEL.setBounds(200, 470, 80, 30);

        jButton_LOGIN.setBackground(new java.awt.Color(0, 204, 204));
        jButton_LOGIN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        jButton_LOGIN.setText("Next");
        jButton_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LOGINActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_LOGIN);
        jButton_LOGIN.setBounds(330, 470, 80, 30);

        jLabelRegisterx.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRegisterx.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegisterx.setText("Back to home page");
        jLabelRegisterx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegisterx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterxMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelRegisterx);
        jLabelRegisterx.setBounds(430, 530, 220, 20);

        jLabelRegister1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRegister1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegister1.setText("Input your password:");
        jLabelRegister1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegister1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabelRegister1);
        jLabelRegister1.setBounds(20, 120, 220, 20);

        jTextField2.setText("jTextField2");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(60, 630, 80, 20);

        jButton62.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\200px-_3_35x35.jpg")); // NOI18N
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton62);
        jButton62.setBounds(30, 190, 40, 40);

        jButton58.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_b.svg_35x35.png")); // NOI18N
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton58);
        jButton58.setBounds(110, 190, 40, 40);

        jButton59.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_c.svg_35x35.png")); // NOI18N
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton59);
        jButton59.setBounds(190, 190, 40, 40);

        jButton60.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_ch.svg_35x35.png")); // NOI18N
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton60);
        jButton60.setBounds(270, 190, 40, 40);

        jButton61.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_dd.svg_35x35.png")); // NOI18N
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton61);
        jButton61.setBounds(350, 190, 40, 40);

        jButton43.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_h.svg_35x35.png")); // NOI18N
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton43);
        jButton43.setBounds(410, 190, 40, 40);

        jButton44.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_m.svg_35x35.png")); // NOI18N
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton44);
        jButton44.setBounds(480, 190, 40, 40);

        jButton51.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_ss.svg_35x35.png")); // NOI18N
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton51);
        jButton51.setBounds(550, 190, 40, 40);

        jButton53.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_y.svg_35x35.png")); // NOI18N
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton53);
        jButton53.setBounds(630, 190, 40, 40);

        jButton45.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_n.svg_35x35.png")); // NOI18N
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton45);
        jButton45.setBounds(550, 250, 40, 40);

        jButton54.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_th.svg_35x35.png")); // NOI18N
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton54);
        jButton54.setBounds(550, 310, 40, 40);

        jButton46.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_p.svg_35x35.png")); // NOI18N
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton46);
        jButton46.setBounds(550, 380, 40, 40);

        jButton49.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_s.svg_35x35.png")); // NOI18N
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton49);
        jButton49.setBounds(480, 380, 40, 40);

        jButton50.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_sh.svg_35x35.png")); // NOI18N
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton50);
        jButton50.setBounds(480, 310, 40, 40);

        jButton57.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_t.svg_35x35.png")); // NOI18N
        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton57);
        jButton57.setBounds(480, 250, 40, 40);

        jButton47.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_d.svg_35x35.png")); // NOI18N
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton47);
        jButton47.setBounds(410, 250, 40, 40);

        jButton52.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_ph.svg_35x35.png")); // NOI18N
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton52);
        jButton52.setBounds(410, 310, 40, 40);

        jButton48.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_r.svg_35x35.png")); // NOI18N
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton48);
        jButton48.setBounds(410, 380, 40, 40);

        jButton36.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\Devanagari_bh.svg_35x35.png")); // NOI18N
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton36);
        jButton36.setBounds(350, 380, 40, 40);

        jButton66.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_nn.svg_35x35.png")); // NOI18N
        jButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton66ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton66);
        jButton66.setBounds(350, 310, 40, 40);

        jButton41.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_jh.svg_35x35.png")); // NOI18N
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton41);
        jButton41.setBounds(350, 250, 40, 40);

        jButton40.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_j.svg_35x35.png")); // NOI18N
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton40);
        jButton40.setBounds(270, 250, 40, 40);

        jButton65.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_ng.svg_35x35.png")); // NOI18N
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton65);
        jButton65.setBounds(270, 310, 40, 40);

        jButton35.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_v.svg_35x35.png")); // NOI18N
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton35);
        jButton35.setBounds(270, 380, 40, 40);

        jButton34.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_tth.svg_35x35.png")); // NOI18N
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton34);
        jButton34.setBounds(190, 380, 40, 40);

        jButton64.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_l.svg_35x35.png")); // NOI18N
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton64);
        jButton64.setBounds(190, 310, 40, 40);

        jButton39.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_gh.svg_35x35.png")); // NOI18N
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton39);
        jButton39.setBounds(190, 250, 40, 40);

        jButton38.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_g.svg_35x35.png")); // NOI18N
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton38);
        jButton38.setBounds(110, 250, 40, 40);

        jButton63.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_kh.svg_35x35.png")); // NOI18N
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton63);
        jButton63.setBounds(110, 310, 40, 40);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_tt.svg_35x35.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(110, 380, 40, 40);

        jButton37.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_ny.svg_35x35.png")); // NOI18N
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton37);
        jButton37.setBounds(30, 380, 40, 40);

        jButton67.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_k.svg_35x35.png")); // NOI18N
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton67);
        jButton67.setBounds(30, 310, 40, 40);

        jButton42.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajendra Sharma\\Documents\\NetBeansProjects\\LoginRegister\\src\\ka kha gha\\1200px-Devanagari_ddh.svg_35x35.png")); // NOI18N
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton42);
        jButton42.setBounds(30, 250, 40, 40);

        jLabelRegister2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRegister2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegister2.setText("Register");
        jLabelRegister2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegister2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabelRegister2);
        jLabelRegister2.setBounds(30, 530, 220, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButton_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CANCELActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_CANCELActionPerformed

    private void jLabelRegisterxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterxMouseClicked
StartForm st = new StartForm();
        st.setVisible(true);
        st.pack();
        st.setLocationRelativeTo(null);
        st.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabelRegisterxMouseClicked

    private void jButton_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LOGINActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String uname = jTextField1.getText();
        String gpass = pass;
        
        
        String query = "SELECT * FROM `java_login_register` WHERE `u_uname` =? AND `u_pass` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, uname);
            ps.setString(2, gpass);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                new ShuffleButtons(uname);
        ShuffleButtons sp  = new ShuffleButtons();
          
                this.dispose();
            
        } 
            else{
                jTextField1.setText("");
                pass="";
                    JOptionPane.showMessageDialog(null, "Incorrect Username Or Password", "Login Failed", 2);
            i++;    
            }
        } 
        
         catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(i>2){
            
            JOptionPane.showMessageDialog(null, "Incorrect Username Or Password .Total attempts achieved.", "Login Failed", 2);
            StartForm st = new StartForm();
        st.setVisible(true);
        st.pack();
        st.setLocationRelativeTo(null);
        st.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        }
       
    }//GEN-LAST:event_jButton_LOGINActionPerformed

    private void jLabelRegister1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegister1MouseClicked
        // TODO add your handling code here:
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelRegister1MouseClicked

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        // TODO add your handling code here:
        pass=pass+"A";
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        // TODO add your handling code here:
        pass=pass+"B";
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        // TODO add your handling code here:
        pass=pass+"C";
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        // TODO add your handling code here:
        pass=pass+"D";
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        // TODO add your handling code here:
        pass=pass+"E";
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
        pass=pass+"V";
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
        pass=pass+"W";
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
        pass=pass+"e";
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        // TODO add your handling code here:
        pass=pass+"h";
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
        pass=pass+"X";
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        // TODO add your handling code here:
        pass=pass+"g";
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here
        pass=pass+"Y";
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        // TODO add your handling code here:
        pass=pass+"b";
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:
        pass=pass+"d";
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        // TODO add your handling code here:
        pass=pass+"f";
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
        pass=pass+"U";
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        // TODO add your handling code here:
        pass=pass+"Z";
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:
        pass=pass+"a";
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        pass=pass+"T";
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton66ActionPerformed
        // TODO add your handling code here:
        pass=pass+"O";
    }//GEN-LAST:event_jButton66ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
        pass=pass+"J";
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
        pass=pass+"I";
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        // TODO add your handling code here:
        pass=pass+"N";
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        pass=pass+"S";
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        pass=pass+"R";
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        // TODO add your handling code here:
        pass=pass+"M";
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
        pass=pass+"H";
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
        pass=pass+"G";
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        // TODO add your handling code here:
        pass=pass+"L";
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pass=pass+"Q";
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        pass=pass+"P";
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        // TODO add your handling code here:
        pass=pass+"K";
    }//GEN-LAST:event_jButton67ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
        pass=pass+"F";
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jLabelRegister2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegister2MouseClicked
RegisterForm rgf = new RegisterForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelRegister2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton_CANCEL;
    private javax.swing.JButton jButton_LOGIN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelRegister1;
    private javax.swing.JLabel jLabelRegister2;
    private javax.swing.JLabel jLabelRegisterx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
